### ISSUE TITLE
Calculate "most likely civic association" for each block_group and tract

### ISSUE THREAD

**Issue by allenbaron** [DataKind-DC/EcoAction#1]
**Goal**
Determine if demographic information, available for census block groups, can be translated to Arlington County civic associations.

This issue needs to be completed soon.

**Comment by icanhazcodeplz** [comment]
If we are okay with [census tracts](https://gisdata-arlgis.opendata.arcgis.com/datasets/census-tract-2010-polygons?geometry), then this is done. Compare to the [civic associations](https://gisdata-arlgis.opendata.arcgis.com/datasets/civic-association-polygons?geometry). There are 59 tracts vs 62 civic associations. I was able to pull the demographic data for the census tracts. See [data/demographics_tract.csv](https://github.com/DataKind-DC/EcoAction/blob/main/data/demographics_tract.csv).

**Comment by icanhazcodeplz** [comment]
I included one idea for the implementation of this in [scripts/most_likely_civ_assoc.R](https://github.com/DataKind-DC/EcoAction/blob/main/scripts/most_likely_civ_assoc.R)

**Comment by allenbaron** [comment]
Instead of union this should probably use intersection but `sf::st_intersection()` unexpectedly creates different polygons depending on the order of input. This appears to be sure to the underlying library (GEOS).

Still need to explore the difference to see how much it matters. As an alternative we could try the slow rasterized approach with `frasterize`.

**Comment by Chellison** [comment]
Maybe 'st_interpolate_aw' could be useful. The description is 'Areal-weighted interpolation of polygon data' and the attributes are:

- x - object of class sf, for which we want to attributes
- to- object of class sf or sfc, with the target geometries
- extensive- logical; if TRUE, the attribute variables are assumed to be spatially extensive (like population) and the sum is preserved, otherwise, spatially intensive (like population density) and the mean is preserved.

**Comment by allenbaron** [comment]
I plan to split block groups by their intersection with civic associations using QGIS after we hear back from EcoAction about the residential areas that are not part of a civic association. Then, we can take a look at how the block groups split and decide how to manage them _within_ each civic association.

**Comment by allenbaron** [comment]
If we decide to go with areal interpolation, the `areal` package may be a better option that what's available in `sf`. Check out the [vignette](https://cran.r-project.org/web/packages/areal/vignettes/areal.html).

**Comment by allenbaron** [comment]
EcoAction said its okay if block groups overlap multiple civic association and we've already translated the demographics so this is complete.
