### ISSUE TITLE
Maps of demographic and canopy data at "block_group" and "civic_association" level

### ISSUE THREAD

**Issue by icanhazcodeplz** [DataKind-DC/EcoAction#10]
Separate layers for each column that is loaded from the function `load_geo_data_for_map(<geo>)`. See `scripts/map_example.R` to get started.

**Comment by icanhazcodeplz** [comment]
We now have a first draft of estimated civic association demographics (see [demographics_civic_association.csv](https://github.com/DataKind-DC/EcoAction/blob/main/data/demographics/demographics_civic_association.csv). Use that instead of "tract".

I'll work on this a bit today, in an effort to get some maps to show EcoAction soon. I'll build off of [demographics_canopy_map.R](https://github.com/DataKind-DC/EcoAction/blob/main/scripts/demographics_canopy_map.R)

Since EcoAction peeps have slow computers, I'll try to make single graphs (instead of the awesome overlay @Chellison made 😢 ), add a legend, and print to PDF (or something that keeps the file size pretty small, say, less than 1MB?).

**Comment by allenbaron** [comment]
This deliverable has been refined and outlined in issue #25.
